void (*destructor)(unsigned int);
void (*SetId)(unsigned long);
void (*ResetUpdateTimes)(unsigned long, unsigned long);
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSStore* (*AsNWSStore)(void);
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSStore* (*AsNWSStore)(void);
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
CNWSAreaOfEffectObject* (*AsNWSAreaOfEffect)(void));
void (*AIUpdate)(void);
int (*ClearAction)(void *_CNWSActionNode, int);
